### ISSUE TITLE
Relatively high CPU usage when HTTP target is enabled

### ISSUE THREAD

**Issue by Charles-YYH** [DarekDan/NLog.Targets.HTTP#15]
Hello,

## Problem
I've just setup a simple configuration using HTTP target, and I've noticed a relatively high CPU usage. A constant CPU usage of about 3% - 5% was observed.

## Current Configuration
Nlog.config
```xml
<?xml version="1.0" encoding="utf-8"?>
<nlog
    xmlns="https://www.nlog-project.org/schemas/NLog.xsd"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <extensions>
        <add assembly="NLog.Targets.Http" />
    </extensions>
    <target name='http_target'
            type='HTTP'
            URL='https://url'
            Authorization='secret'
            BatchSize="50">
        <layout type='JsonLayout'>
            <attribute name='host' layout='${machinename}' />
            <attribute name='level' layout='${level:upperCase=true}' />
            <attribute name='message' layout='${message}' />
            <attribute name='timestamp' layout='${longdate:universalTime=true}' />
            <attribute name='meta_data' encode='false'>
                <layout type='JsonLayout'>
                    <attribute name='thread' layout='${threadid}' />
                    <attribute name='callsite' layout='${callsite:className=true:fileName=true:includeSourcePath=false:methodName=true}' />
                </layout>
            </attribute>
        </layout>
    </target>
    <rules>
        <logger name="*" minlevel="Error" writeTo="http_target" />
    </rules>
</nlog>
```

## Investigation
It seems that changing `timeToSleepBetweenBatches` attribute didn't have any effect, I've tried to set it to value 0 or 1 and the problem remains. 

After reading the source code, I've noticed a potential cause of this problem. For this line [Http.cs#L254](https://github.com/DarekDan/NLog.Targets.HTTP/blob/master/NLog.Targets.Http/HTTP.cs#L254),  it will wait for 1ms each time in the loop.  
Does this mean the logger will be fired at least every 1ms ?

## Environment
- dotnet 5.0.101
- NLog 4.7.9
- NLog.Targets.Http 1.0.5

Perhaps the problem happens because of a mis-configuration of the nlog.config, any help would be appreciated.

Thanks,
Charles Y

**Comment by DarekDan** [comment]
Was it something else?

**Comment by Charles-YYH** [comment]
I can not reproduce this behavior every time, so I closed this issue in the case that I was wrong on it.

Still investigating.
