### ISSUE TITLE
[bug] Unknown exception occured Exception when use1.0.5 in netcore3.1

### ISSUE THREAD

**Issue by vl00** [DarekDan/NLog.Targets.HTTP#17]
use 1.0.5 in netcore3.1, I found a error:

Warn Unknown exception occured Exception: System.ArgumentException: Object must be the same type as the enum. The type passed in was 'System.Int32'; the enum type was 'System.Net.HttpStatusCode'.
at System.Enum.CompareTo(Object target)
at NLog.Targets.Http.HTTP.SendFast(String message)

and then my http log was repeat to called many times!

**Comment by hakakou** [comment]
I am getting the same error when using in an Android Xamarin app. Downgrading to 1.0.4 fixes the problem.

**Comment by DarekDan** [comment]
ACK

**Comment by DarekDan** [comment]
1.0.6 has been published

**Comment by DarekDan** [comment]
Let me confirm with a quick test

**Comment by DarekDan** [comment]
Hold ...
Found a problem

**Comment by DarekDan** [comment]
OK, 1.0.7 resolves it
