### ISSUE TITLE
Any chance of a .NET Standard 2.0 build?

### ISSUE THREAD

**Issue by SteveHarveyUK** [DarekDan/NLog.Targets.HTTP#22]
We'd like to use this package within a .NET Standard 2.0 library that's used across .NET Framework v4.7.2 and .NET Core based on the age of the projects.
We're seeing some warnings as the build is trying to use the .NET Framework version as there's no .NET Standard v2.0 version.

`  XXXXX.csproj: [NU1701] Package 'NLog.Targets.Http 1.0.7' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.`

**Comment by DarekDan** [comment]
I will take a look if I can bring 2.0 back.

**Comment by DarekDan** [comment]
Version 1.0.8 uploaded to NuGet. Being validated.

**Comment by SteveHarveyUK** [comment]
Thanks @DarekDan - that's a seriously fast response. :-)
