### ISSUE TITLE
Flushing and Batching Create Invalid JSON

### ISSUE THREAD

**Issue by ginadi011** [DarekDan/NLog.Targets.HTTP#23]
When using this library along with a JSONLayout batching and flushing create invalid json that causes a 400 request from the endpoint, because the json does not get wrapped in an array.

Code sample:
`    <target name='test' 
            type='HTTP' 
            URL=''
           Method='POST'
            BatchSize='3'
            FlushBeforeShutdown='true'>
   <layout type='JsonLayout'>
        <attribute name='sourcetype' layout='_json' />
        <attribute name='host' layout='${machinename}' />
        <attribute name='event' encode='false'>
          <layout type='JsonLayout'>
            <attribute name='level' layout='${level:upperCase=true}' />
            <attribute name='source' layout='${logger}' />
            <attribute name='thread' layout='${threadid}' />
            <attribute name='message' layout='${message}' />
            <attribute name='utc' layout='${date:universalTime=true:format=yyyy-MM-dd HH\:mm\:ss.fff}' />
          </layout>
</target>`

Post request output (causes 400 bad request):
{"sourcetype":"_json", "host":"","event":{"level":"INFO", "source":"","thread:"1","message":"test","utc":"2021-10-05 15:01:01.375"}}
{"sourcetype":"_json", "host":"","event":{"level":"INFO", "source":"","thread:"1","message":"test","utc":"2021-10-05 15:01:01.375"}}
{"sourcetype":"_json", "host":"","event":{"level":"INFO", "source":"","thread:"1","message":"test","utc":"2021-10-05 15:01:01.375"}}

**Comment by DarekDan** [comment]
From my own testing, if the messages are separated by a new line, they are correctly recognized by Splunk. I will try to deploy on Docker and see if that works. I do recall that sending arrays definitely did not work.

**Comment by DarekDan** [comment]
So here is my test case:
![image](https://user-images.githubusercontent.com/5083576/138602030-fdbb0dc0-8234-4659-89b9-5bf81e8b78fa.png)

And the results in Splunk:
![image](https://user-images.githubusercontent.com/5083576/138602046-b7a4e130-a45c-49bf-87c3-9aa92d9ae6ef.png)

If you have clarification how to send multiple messages in a single POST, I am all ears.

**Comment by DarekDan** [comment]
Even the Splunk docs show an invalid JSON to be posted: https://docs.splunk.com/Documentation/Splunk/8.2.2/Data/HECExamples

**Comment by DarekDan** [comment]
Confirmed, while the JSON can be invalid it is what Splunk expects. Do you have another HTTP target that requires the JSON to be passes as an array?

**Comment by DarekDan** [comment]
New feature added in 1.0.15 allowing batching as JSON array. Splunk HEC rejects it.
