### ISSUE TITLE
msg will not be sent anymore after a http exception occurs or the http responsecode is not equal 200

### ISSUE THREAD

**Issue by wuuer** [DarekDan/NLog.Targets.HTTP#30]
the flag _hasHttpError keeps TRUE after a http exception occurs or the http responsecode is not equal 200
so ProcessChunk method will not invoke anymore

**Comment by DarekDan** [comment]
I will look into it.

Sent from my iPhone

On Dec 17, 2021, at 4:17 AM, wuuer ***@***.***> wrote:

﻿

the flag _hasHttpError keeps FALSE after a http exception occurs or the http responsecode is not equal 200
so ProcessChunk method will not invoke anymore

**Comment by DarekDan** [comment]
Resolved in 1.0.17
