### ISSUE TITLE
NLog.Targets.HTTP.dll does not have a strong name

### ISSUE THREAD

**Issue by vmschmaedek** [DarekDan/NLog.Targets.HTTP#4]
I'm try to install the dll on GAC, because we have many applications that will use it, but get the error:
"Failure adding assembly to the cache: Attempt to install an assembly without a strong name"

**Comment by DarekDan** [comment]
Do you require signed assemblies? Because there are consequences to it: https://docs.microsoft.com/en-us/dotnet/standard/assembly/create-use-strong-named

**Comment by vmschmaedek** [comment]
GAC register requires signed assemblies. The NLOG itself is signed and we register it in GAC, so we wanna to register NLog.Targets.HTTP as well.

**Comment by DarekDan** [comment]
I hope I've done it right ... first time ... 1.0.4 published.

**Comment by DarekDan** [comment]
Assuming closed.
