### ISSUE TITLE
ContentType is null if not explicitly specified

### ISSUE THREAD

**Issue by chefarbeiter** [DarekDan/NLog.Targets.HTTP#41]
The documentation says that `application/json` is the default value for `ContentType`:
https://github.com/DarekDan/NLog.Targets.HTTP/blob/aafc0877556e916eaf1fbc79da7e6ef53cee9d64/README.md?plain=1#L82

But this does not work as expected. If i omit the `ContentType` setting in my nlog configuration, the HTTP requests are sent with `ContentType` = `null`.

In the code, the `_contentType` field is initialized to the default value, but not `_contentTypeHeader`:
https://github.com/DarekDan/NLog.Targets.HTTP/blob/aafc0877556e916eaf1fbc79da7e6ef53cee9d64/NLog.Targets.Http/HTTP.cs#L60-L61

The latter is only set in the `ContentType` setter, which is never called if the setting is not specified in the configuration:
https://github.com/DarekDan/NLog.Targets.HTTP/blob/aafc0877556e916eaf1fbc79da7e6ef53cee9d64/NLog.Targets.Http/HTTP.cs#L125-L134

For the actual request, `_contentTypeHeader` is used, which is null in the default case:
https://github.com/DarekDan/NLog.Targets.HTTP/blob/aafc0877556e916eaf1fbc79da7e6ef53cee9d64/NLog.Targets.Http/HTTP.cs#L348

**Comment by snakefoot** [comment]
@DarekDan Possible to get a release of `NLog.Targets.HTTP` that includes the fix #46 ?
