### ISSUE TITLE
Error Instantiating Extension Using nlog.config

### ISSUE THREAD

**Issue by dbeardsley-fi** [DarekDan/NLog.Targets.HTTP#49]
I am trying to use this extension with the UiPath application to send log events to Splunk.

I've copied the extsension assembly to the UiPath Studio folder, where the NLog.dll resides, and updated the UiPath nlog.config file to reference the extension.
 
At runtime, I see the following error logged:

Exception: NLog.NLogConfigurationException: Failed to create Target of type: HTTP ---> System.ArgumentException: Target symbol-name is unknown: 'HTTP'
   at NLog.Config.Factory`2.CreateInstance(String itemName)
   at NLog.Config.LoggingConfigurationParser.FactoryCreateInstance[T](String classType, INamedItemFactory`2 factory)

Any insights into what the problem might be would be greatly appreciated.

Here is my config file, with the Splunk token and URL removed:

`<?xml version="1.0" encoding="utf-8" ?>
<nlog 
    autoReload="true"
    xmlns="http://www.nlog-project.org/schemas/NLog.xsd" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	throwExceptions="true" 
	internalLogFile="C:\Temp\nlog-internal.log" 
	internalLogLevel="Trace" 
	internalLogToConsole="true">
    <extensions>
        <add assembly="NLog.Targets.Http"/>
    </extensions>  
    <variable name="WorkflowLoggingDirectory" value="${specialfolder:folder=LocalApplicationData}/UiPath/Logs" />
    <targets>
        <target xsi:type="File" name="WorkflowLogFiles" fileName="${WorkflowLoggingDirectory}/${shortdate}_Execution.log" layout="${time} ${level} ${message}" keepFileOpen="true" openFileCacheTimeout="5" concurrentWrites="true" encoding="utf-8" writeBom="true" />
        <target name='splunk' 
                xsi:type='HTTP' 
                Url='splunkurl'
                Method='POST'
                Authorization='Splunk token' 
                IgnoreSslErrors='true'
                FlushBeforeShutdown='true'
                ContentType='application/json'
                Accept='application/json'
                ConnectTimeout='30000' 
                BatchSize='1'>
            <layout type='JsonLayout'>
              <attribute name='sourcetype' layout='_json' />
              <attribute name='host' layout='${machinename}' />
              <attribute name='event' encode='false'>
                <layout type='JsonLayout'>
                  <attribute name='level' layout='${level:upperCase=true}' />
                  <attribute name='source' layout='${logger}' />
                  <attribute name='thread' layout='${threadid}' />
                  <attribute name='message' layout='${message}' />
                  <attribute name='utc' layout='${date:universalTime=true:format=yyyy-MM-dd HH\:mm\:ss.fff}' />
                </layout>
              </attribute>
            </layout>
        </target>
    </targets>
  <rules>
    <logger name="WorkflowLogging" writeTo="WorkflowLogFiles" final="true" />
    <logger name="*" minlevel="Debug" writeTo="splunk" />
  </rules>
</nlog>`

**Comment by snakefoot** [comment]
Have tried to make your `NLog.config`-file easier to read:
```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog  autoReload="true" xmlns="http://www.nlog-project.org/schemas/NLog.xsd"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  throwExceptions="true"  internalLogFile="C:\Temp\nlog-internal.log"  internalLogLevel="Trace"  internalLogToConsole="true">
<extensions><add assembly="NLog.Targets.Http"/></extensions>
<variable name="WorkflowLoggingDirectory" value="${specialfolder:folder=LocalApplicationData}/UiPath/Logs" />
<targets>
   <target xsi:type="File" name="WorkflowLogFiles" fileName="${WorkflowLoggingDirectory}/${shortdate}_Execution.log" layout="${time} ${level} ${message}" keepFileOpen="true" openFileCacheTimeout="5" concurrentWrites="true" encoding="utf-8" writeBom="true" />

   <target name='splunk'  xsi:type='HTTP'  Url='splunkurl' Method='POST' Authorization='Splunk token'  IgnoreSslErrors='true' FlushBeforeShutdown='true' ContentType='application/json' Accept='application/json' ConnectTimeout='30000'  BatchSize='1'>
      <layout type='JsonLayout'>
        <attribute name='sourcetype' layout='_json' />
        <attribute name='host' layout='${machinename}' />
        <attribute name='event' encode='false'>
           <layout type='JsonLayout'>
             <attribute name='level' layout='${level:upperCase=true}' />
             <attribute name='source' layout='${logger}' />
             <attribute name='thread' layout='${threadid}' />
             <attribute name='message' layout='${message}' />
             <attribute name='utc' layout='${date:universalTime=true:format=yyyy-MM-dd HH\:mm\:ss.fff}' />
           </layout>
        </attribute>
      </layout>
   </target>
</targets>
<rules>
   <logger name="WorkflowLogging" writeTo="WorkflowLogFiles" final="true" />
   <logger name="*" minlevel="Debug" writeTo="splunk" />
</rules>
</nlog>
```
The NLog configuration looks valid. Maybe you can also include the output from the [NLog InternalLogger](https://github.com/NLog/NLog/wiki/Internal-Logging) at Debug-Level ? (Maybe there is an issue with loading the `NLog.Targets.Http`-extension).

**Comment by DarekDan** [comment]
Not sure what UiPath is and which DLL have you copied and where. This seems to be related to deployment, possibly version conflict.

**Comment by dbeardsley-fi** [comment]
Using assembly binding logging I was able to get to the bottom of it. In short, no issue with the extension itself. 

I had to match the build to the specific NLog version (5.0.0) and framework (FX 4.6.1) UiPath was using and the assemblies were hosted in a subfolder, which was unexpected.

Thanks
