### ISSUE TITLE
Variables and GDC not supported?

### ISSUE THREAD

**Issue by harrio** [DarekDan/NLog.Targets.HTTP#5]
I'm trying to set the URL and Authorization parameters dynamically but they always end up being set as the placeholder ${var:MyVariable} or ${gdc:item=MyGdcItem} instead of the real value. Are they not supported?

**Comment by harrio** [comment]
Seems they are declared as strings instead of layouts, so I guess that means not supported.

**Comment by DarekDan** [comment]
I've never thought about using it like that. Not sure if it is supported or not but will investigate it.

**Comment by DarekDan** [comment]
This is not that trivial to implement. But doable. Will have to refactor a bunch of code.

**Comment by DarekDan** [comment]
For example, it will need separate queues for each calculated URL. For performance reasons, there is currenlty one HttpClient, whihc does not get reset unless there are changes, so that will also need to be refactored. Lots of work. :|

**Comment by snakefoot** [comment]
@DarekDan If you just changed the logic so ResetHttpClientIfNeeded performed this logic;

```c#
        private void ResetHttpClientIfNeeded()
        {

                var url = Url?.Render(LogEventInfo.CreateNullEvent());
                var proxyUrl = ProxyUrl?.Render(LogEventInfo.CreateNullEvent());

                _handler.UseProxy = !string.IsNullOrWhiteSpace(proxyUrl);
                _httpClient = new HttpClient(_handler)
                {
                    BaseAddress = new Uri(url),
                    Timeout = TimeSpan.FromMilliseconds(ConnectTimeout)
                };

                if (_handler.UseProxy)
                    _handler.Proxy = new WebProxy(new Uri(proxyUrl))
        }
```

Then it would support most scenarios, where Url is loaded from app.config or appsettings.json. Guess the same could be done for ProxyUser + ProxyPassword + Domain  + UserName.

**Comment by lsfera** [comment]
@DarekDan  just linked a trivial PR #14  where I gave you a real world application example

**Comment by DarekDan** [comment]
> @DarekDan If you just changed the logic so ResetHttpClientIfNeeded performed this logic;
> 
> ```cs
>         private void ResetHttpClientIfNeeded()
>         {
> 
>                 var url = Url?.Render(LogEventInfo.CreateNullEvent());
>                 var proxyUrl = ProxyUrl?.Render(LogEventInfo.CreateNullEvent());
> 
>                 _handler.UseProxy = !string.IsNullOrWhiteSpace(proxyUrl);
>                 _httpClient = new HttpClient(_handler)
>                 {
>                     BaseAddress = new Uri(url),
>                     Timeout = TimeSpan.FromMilliseconds(ConnectTimeout)
>                 };
> 
>                 if (_handler.UseProxy)
>                     _handler.Proxy = new WebProxy(new Uri(proxyUrl))
>         }
> ```
> 
> Then it would support most scenarios, where Url is loaded from app.config or appsettings.json. Guess the same could be done for ProxyUser + ProxyPassword + Domain + UserName.

I'll incorporate in 1.0.6

**Comment by snakefoot** [comment]
> @DarekDan I'll incorporate in 1.0.6

Excellent! But I guess you mean ver. 1.0.5 ?

**Comment by DarekDan** [comment]
No. I still need to update Proxy. And I like the null coalescing operator so I will use it. 1.0.5 was just published.

**Comment by snakefoot** [comment]
Yes the Proxy-Condig (with authorization) is still pending.


But the Url can now be configured with NLog Layout with ver. 1.0.5.

**Comment by DarekDan** [comment]
Added support for ProxyUrl in 1.0.10.

**Comment by DarekDan** [comment]
Resolved in 1.0.13 ?

**Comment by danielkraut** [comment]
I have found this closed issue and I don't think it works as expected. Can you change the URL in runtime dynamically? I am able to use NLog variables in the config and set those variables during setup phase, but once a logger has been used and the HTTP extension initialized, changing my variables does nothing to the URL property. It can only be set once on startup. Is this expected behavior? @DarekDan

**Comment by snakefoot** [comment]
@danielkraut Right now HTTP-target will only react to `Url`-property being assigned directly (So the NLog Layout only behaves at expected at startup). I guess it could be a simple change to make it fully support NLog Layout (Like NLog [WebService-target](https://github.com/NLog/NLog/wiki/WebService-target))
