### ISSUE TITLE
UnixTimeLayoutRenderer appears to be outputting local time instead of UTC time.

### ISSUE THREAD

**Issue by patkae** [DarekDan/NLog.Targets.HTTP#7]
I'm not sure if the ${unixtime} layout is ready for use but I tried it out and it is rendering seconds based on local time instead of UTC time.

I have also tried setting the NLog time source to FastUTC and that doesn't make a difference.

**Comment by DarekDan** [comment]
I am not sure that Unix time is supposed to mean UTC by default.

**Comment by DarekDan** [comment]
Back in 2011, even regular dates were using this format to conevrt to UTC: ${date:universalTime=true}

**Comment by DarekDan** [comment]
In other words, I do not have a unixtime to UTC converter yet. It's always local.

**Comment by DarekDan** [comment]
I will look into it or you can submit a PR.

**Comment by DarekDan** [comment]
Available in 1.0.3

**Comment by patkae** [comment]
Thank you for the rapid response. I needed this because Splunk requires UTC time for the epoch.
